# Generated by Django 3.2.25 on 2024-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='carrots'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.TextField(default='balenced'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.TextField(default='1kg'),
            preserve_default=False,
        ),
    ]
