# Generated by Django 3.2.25 on 2024-04-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
