# Generated by Django 3.2.25 on 2024-05-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
